apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# - https://github.com/argoproj/argo-workflows/releases/download/v3.1.7/install.yaml
- argo-workflow.yaml
- workflow-role-binding.yaml
- workflow-role.yaml

patchesStrategicMerge:
- argo-server-service.yaml
- workflow-controller-cm.yaml
- argo-binding.yaml
- argo-server-binding.yaml
