apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: minio
spec:
  minio:
    example:
      bucket:
        name: demo
      endpoint: demo-minio.demo.svc.cluster.local:9000
      events:
        - s3:ObjectCreated:Put
      insecure: true
      filter:
        suffix: ".jpg"
      accessKey:
        name: demo-minio
        key: accesskey
      secretKey:
        name: demo-minio
        key: secretkey
